# Generated by Django 4.2.30 on 2026-10-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
    ]
